name: Go CI

on:
  pull_request:
    paths:
      - "go-app/**"
      - ".github/workflows/go-ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Go (with built-in caching)
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache: true

      # 3. Install deps
      - run: cd go-app && go mod tidy && go mod download

      # 4. Lint
      - name: Run Linter
        run: |
          cd go-app
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run ./...

      # 5. Build
      - run: cd go-app && go build ./...

      # 6. Test with coverage
      - run: cd go-app && go test -v -coverprofile=coverage.out ./...

      # 7. Upload artifact (coverage report)
      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: go-coverage
          path: go-app/coverage.out
