# This workflow runs Python CI checks on pull requests affecting the python-app directory.
# It sets up Python, installs dependencies, and runs tests using pytest.

name : Python CI

on :
  push:
    paths:
      - "python-app/**"
      - ".github/workflows/python-ci.yml"
  pull_request:
    paths:
      - 'python-app/**'
      - '.github/workflows/python-ci.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: Actions/checkout@v2
      
      # 2. Set up Python
      - name: Set up Python
        uses: Actions/setup-python@v2
        with:
          python-version:'3.10'
      
      # 3. Install dependencies
      - name: Install dependencies
        runs: |
          python -m pip install --upgrade pip
          pip install -r python-app/requirements.txt
      
      # 4. Run tests
      - name: Run tests
        run: |
          cd python-app
          pytest -v 